[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x3e42a9746e6c8f868f71a4353ec5d198f0dd1af26f95bd51e2e005358ae14fd"
transaction_hash = "0x6a12bc71cd1976ded6c91c8478e74ef92dce66e6ecfe26f11c1008af2b9a9c"
block_number = 3
seed = "karat"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x2ec22a653460527eacb3b74c07eeb0606a9c47db5f450d140a14f0a0a117e76"
class_hash = "0x7fc5730fa6ae6281da230acee7af1921057cab8cabc4af28d8183b9c0630df"
original_class_hash = "0x7fc5730fa6ae6281da230acee7af1921057cab8cabc4af28d8183b9c0630df"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"

[[contracts]]
kind = "DojoContract"
address = "0x3bac2791460aec9d2ce62787c07c4d8c728fbc01ccd48f120f47380bd4ea65a"
class_hash = "0x7439affc76abdd5c9b330badc87942f4673df587d8210ced4abb367f9985381"
original_class_hash = "0x7439affc76abdd5c9b330badc87942f4673df587d8210ced4abb367f9985381"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/karat_systems_minter_minter.json"
reads = []
writes = [
    "Config",
    "Seed",
]
computed = []
init_calldata = [
    "$contract_address:karat::systems::karat_token::karat_token",
    "512",
    "1",
]
name = "karat::systems::minter::minter"

[[models]]
kind = "DojoModel"
class_hash = "0x22c65e8e896257819191be93cbe76be316102b9314811b88aa8395646958073"
original_class_hash = "0x22c65e8e896257819191be93cbe76be316102b9314811b88aa8395646958073"
abi = "manifests/dev/abis/deployments/models/karat_models_config_config.json"
name = "karat::models::config::config"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "painter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "max_supply"
type = "u128"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x604ffab2db12a3094c2ffb5e8791bb89d38621303a0a1220603274ab4336f4c"
original_class_hash = "0x604ffab2db12a3094c2ffb5e8791bb89d38621303a0a1220603274ab4336f4c"
abi = "manifests/dev/abis/deployments/models/karat_models_seed_seed.json"
name = "karat::models::seed::seed"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x44a95fb54f9ce628af8d3a9308f6da9331a3504c4e93122fd28988b41e82632"
original_class_hash = "0x44a95fb54f9ce628af8d3a9308f6da9331a3504c4e93122fd28988b41e82632"
abi = "manifests/dev/abis/deployments/models/karat_systems_metadata_erc_721_meta_model.json"
name = "karat::systems::metadata::erc_721_meta_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
original_class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
abi = "manifests/dev/abis/deployments/models/token_components_security_initializable_initializable_model.json"
name = "token::components::security::initializable::initializable_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x762ff8a2da45cda62e2bf84276e2f7378b9b158bce2a0478c96b8dfd5c073b1"
original_class_hash = "0x762ff8a2da45cda62e2bf84276e2f7378b9b158bce2a0478c96b8dfd5c073b1"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_approval_erc_721_operator_approval_model.json"
name = "token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x56e53c34b6bca04bc5c2f4fe66e19320d2290a8e0561867ef1f9329f3944f1d"
original_class_hash = "0x56e53c34b6bca04bc5c2f4fe66e19320d2290a8e0561867ef1f9329f3944f1d"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_approval_erc_721_token_approval_model.json"
name = "token::components::token::erc721::erc721_approval::erc_721_token_approval_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e44c64b3fe31a10c990df6329b3b37c49e35c34ab8c72a77b2f97dc57a4d67"
original_class_hash = "0x1e44c64b3fe31a10c990df6329b3b37c49e35c34ab8c72a77b2f97dc57a4d67"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_balance_erc_721_balance_model.json"
name = "token::components::token::erc721::erc721_balance::erc_721_balance_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2659b781469f378092758cb186b55141668bde6ed97751c8e2290be85190cda"
original_class_hash = "0x2659b781469f378092758cb186b55141668bde6ed97751c8e2290be85190cda"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_index_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6eb61f3bca048d7ac7e518cb65393ac8448fbe7a67ab4ea1aa113248626cb8b"
original_class_hash = "0x6eb61f3bca048d7ac7e518cb65393ac8448fbe7a67ab4ea1aa113248626cb8b"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_owner_index_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x97cdab02d16c364982907d3c12a154f064a25321371220086d42c911d0ddd8"
original_class_hash = "0x97cdab02d16c364982907d3c12a154f064a25321371220086d42c911d0ddd8"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_owner_token_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7ba4b1baa744624ba5f68f35d8d09c0eec899eb543d423c0312505b18bf81dd"
original_class_hash = "0x7ba4b1baa744624ba5f68f35d8d09c0eec899eb543d423c0312505b18bf81dd"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_token_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x254d52feafeeabcf794133e9fc1eeb0b0d5d7089189e400b989706b192c7ad9"
original_class_hash = "0x254d52feafeeabcf794133e9fc1eeb0b0d5d7089189e400b989706b192c7ad9"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_enumerable_erc_721_enumerable_total_model.json"
name = "token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x27460face6d6a51b72dd84872a719b04d479f03d87ab08ece2a8495e385a82e"
original_class_hash = "0x27460face6d6a51b72dd84872a719b04d479f03d87ab08ece2a8495e385a82e"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc721_erc721_owner_erc_721_owner_model.json"
name = "token::components::token::erc721::erc721_owner::erc_721_owner_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false
