kind = "DojoContract"
class_hash = "0x1a41503b68d679caa0c9925e9033083385cef47309d72455bb1728444ebc771"
original_class_hash = "0x1a41503b68d679caa0c9925e9033083385cef47309d72455bb1728444ebc771"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"
