kind = "DojoContract"
class_hash = "0x7fcc518a71ac318b166d697ede3454335af09c2f8475b15fc237f48ad66a4b0"
original_class_hash = "0x7fcc518a71ac318b166d697ede3454335af09c2f8475b15fc237f48ad66a4b0"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = []
init_calldata = []
tag = "karat-karat_token"
systems = [
    "mint",
    "burn",
    "karat_init",
    "emit_metadata_update",
    "emit_batch_metadata_update",
]
manifest_name = "karat-karat_token-6eea4d34"
