kind = "DojoContract"
class_hash = "0x76bb21d4c7cada7f4cc6f44a403c3eb442eadc3dc56bc28631969ce09b0308f"
original_class_hash = "0x76bb21d4c7cada7f4cc6f44a403c3eb442eadc3dc56bc28631969ce09b0308f"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/karat_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::minter::minter"
