kind = "DojoContract"
class_hash = "0x3070ef774baee12e79e80b64f1ebec122da9000a980560fcceb524ad353e7de"
original_class_hash = "0x3070ef774baee12e79e80b64f1ebec122da9000a980560fcceb524ad353e7de"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = []
init_calldata = []
tag = "karat-minter"
systems = [
    "set_open",
    "assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"
