[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x4c0970c9f52045ef8eeedd1e11265ebb69ed90fce58c96ad103aecf7f91302a"
transaction_hash = "0x44cd3ed294de500e3661738c1b4d1b83f7378c34dd0bde8abccd7df642ae9ed"
seed = "512karat"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://api.cartridge.gg/rpc/starknet-sepolia"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x410af9215196e74822373a0ca51854a420005360f36e2893b9612676a0f49cb"
class_hash = "0x709d1aeeb211e41b12f308f76a9ddc2c8593909ba61cb552febff69635955a7"
original_class_hash = "0x709d1aeeb211e41b12f308f76a9ddc2c8593909ba61cb552febff69635955a7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = [
    "origami_token-SRC5Model",
    "origami_token-InitializableModel",
    "origami_token-ERC721OwnerModel",
    "origami_token-ERC721BalanceModel",
    "origami_token-ERC721MetaModel",
    "origami_token-ERC721EnumerableIndexModel",
    "origami_token-ERC721EnumerableOwnerIndexModel",
    "origami_token-ERC721EnumerableOwnerTokenModel",
    "origami_token-ERC721EnumerableTokenModel",
    "origami_token-ERC721EnumerableTotalModel",
    "origami_token-ERC721TokenApprovalModel",
    "origami_token-ERC721OperatorApprovalModel",
]
init_calldata = []
tag = "karat-karat_token"
systems = [
    "initialize",
    "mint",
    "burn",
]
manifest_name = "karat-karat_token-6eea4d34"

[[contracts]]
kind = "DojoContract"
address = "0x2b1cb5c53db5f07974585b8788ec4f4b57f732c71c4a0e66b8b282fdca29889"
class_hash = "0xb8318f43fd776835901c7d1554ff3ae460d4c73f49163f225de6b109bc4088"
original_class_hash = "0xb8318f43fd776835901c7d1554ff3ae460d4c73f49163f225de6b109bc4088"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = [
    "karat-Config",
    "karat-Seed",
]
init_calldata = [
    "$contract_address:karat-karat_token",
    "512",
    "1",
]
tag = "karat-minter"
systems = [
    "set_open",
    "assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"

[[models]]
kind = "DojoModel"
class_hash = "0x68a476d1a6443fdf9be1883ab0169929af2871ac9257bd091201eb292b9653b"
original_class_hash = "0x68a476d1a6443fdf9be1883ab0169929af2871ac9257bd091201eb292b9653b"
abi = "manifests/sepolia/deployment/abis/models/karat-Config-4fe722d0.json"
tag = "karat-Config"
qualified_path = "karat::models::config::config"
manifest_name = "karat-Config-4fe722d0"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "painter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "max_supply"
type = "u128"
key = false

[[models.members]]
name = "cool_down"
type = "bool"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
original_class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
abi = "manifests/sepolia/deployment/abis/models/karat-Seed-5904bdd8.json"
tag = "karat-Seed"
qualified_path = "karat::models::seed::seed"
manifest_name = "karat-Seed-5904bdd8"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36dc2b76dcd77b58fe987c0b8836c2ce7fa08cb9d44838634218fad353bec83"
original_class_hash = "0x36dc2b76dcd77b58fe987c0b8836c2ce7fa08cb9d44838634218fad353bec83"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721BalanceModel-246a8e17.json"
tag = "origami_token-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "origami_token-ERC721BalanceModel-246a8e17"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d3394057bbdf2262c0ba952ec0bbc13b8a315ad8bd9e684650225abc4152ac"
original_class_hash = "0x5d3394057bbdf2262c0ba952ec0bbc13b8a315ad8bd9e684650225abc4152ac"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableIndexModel-1a4200e7.json"
tag = "origami_token-ERC721EnumerableIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"
manifest_name = "origami_token-ERC721EnumerableIndexModel-1a4200e7"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fd76867b943befb036da828bd1d2bec2386863ad70aafa770360c5b3e9acfc"
original_class_hash = "0x2fd76867b943befb036da828bd1d2bec2386863ad70aafa770360c5b3e9acfc"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableOwnerIndexModel-573cb336.json"
tag = "origami_token-ERC721EnumerableOwnerIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"
manifest_name = "origami_token-ERC721EnumerableOwnerIndexModel-573cb336"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x45871731d39993b19571f03348d6932fba0445f6eb94e1e37d2db5c4474d61c"
original_class_hash = "0x45871731d39993b19571f03348d6932fba0445f6eb94e1e37d2db5c4474d61c"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableOwnerTokenModel-74966560.json"
tag = "origami_token-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "origami_token-ERC721EnumerableOwnerTokenModel-74966560"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
original_class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableTokenModel-5c383d9f.json"
tag = "origami_token-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "origami_token-ERC721EnumerableTokenModel-5c383d9f"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x476254a3660ac696486628f6fb9c531a94de4b0addcc00bc43eafc207638968"
original_class_hash = "0x476254a3660ac696486628f6fb9c531a94de4b0addcc00bc43eafc207638968"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableTotalModel-5674a124.json"
tag = "origami_token-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "origami_token-ERC721EnumerableTotalModel-5674a124"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4310a938ba169a6d12cd0aa9dbeaf2992ddc4b55621bdeb883c0b43a3726d6d"
original_class_hash = "0x4310a938ba169a6d12cd0aa9dbeaf2992ddc4b55621bdeb883c0b43a3726d6d"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721MetaModel-423fffaa.json"
tag = "origami_token-ERC721MetaModel"
qualified_path = "origami_token::components::token::erc721::erc721_metadata::erc_721_meta_model"
manifest_name = "origami_token-ERC721MetaModel-423fffaa"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x29f6fcd504ae293bec1139611e0fe870deda9be6a41ef7e1ffacfa5c76c4dd5"
original_class_hash = "0x29f6fcd504ae293bec1139611e0fe870deda9be6a41ef7e1ffacfa5c76c4dd5"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721OperatorApprovalModel-1083d4d1.json"
tag = "origami_token-ERC721OperatorApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"
manifest_name = "origami_token-ERC721OperatorApprovalModel-1083d4d1"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
original_class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721OwnerModel-61577880.json"
tag = "origami_token-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "origami_token-ERC721OwnerModel-61577880"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
original_class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721TokenApprovalModel-560d5854.json"
tag = "origami_token-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "origami_token-ERC721TokenApprovalModel-560d5854"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
original_class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
abi = "manifests/sepolia/deployment/abis/models/origami_token-InitializableModel-5c624096.json"
tag = "origami_token-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_token-InitializableModel-5c624096"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x25d17f5223a69a8f5a4b9bdd2bba1121a9da6e5bdb83592402943158e5946b9"
original_class_hash = "0x25d17f5223a69a8f5a4b9bdd2bba1121a9da6e5bdb83592402943158e5946b9"
abi = "manifests/sepolia/deployment/abis/models/origami_token-SRC5Model-72fc8945.json"
tag = "origami_token-SRC5Model"
qualified_path = "origami_token::components::introspection::src5::src_5_model"
manifest_name = "origami_token-SRC5Model-72fc8945"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "interface_id"
type = "felt252"
key = true

[[models.members]]
name = "supports"
type = "bool"
key = false
