[world]
name = "Karat"
description = "Generative Art made with Dojo."
icon_uri = "https://raw.githubusercontent.com/rsodre/512karat/main/assets/logo.png"
cover_uri = "https://raw.githubusercontent.com/rsodre/512karat/main/assets/splash.png"
website = "https://github.com/rsodre/512karat"
seed = "karat"

[world.socials]
x = "https://x.com/matalecode"
github = "https://github.com/rsodre/512karat"
# discord = "https://discord.gg/xxx"
# telegram = "https://t.me/xxx"

[namespace]
default = "karat"
mappings = { "origami_token" = "origami_karat" }

[env]
rpc_url = "http://localhost:5050"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x294e26b767cb4e3c1f6d03c7f88cbe32212dab01f61a10bdb37403da7108f62"
