[world]
name = "Karat"
description = "Generative Art made with Dojo."
icon_uri = "https://raw.githubusercontent.com/rsodre/512karat/main/assets/logo.png"
cover_uri = "https://raw.githubusercontent.com/rsodre/512karat/main/assets/splash.png"
website = "https://github.com/rsodre/512karat"
seed = "karat"

[world.socials]
x = "https://x.com/matalecode"
github = "https://github.com/rsodre/512karat"
# discord = "https://discord.gg/xxx"
# telegram = "https://t.me/xxx"

[namespace]
default = "karat"
mappings = { "origami_token" = "origami_karat" }

[env]
# rpc_url = "https://my.provider.com/starknet/mainnet/rpc" # STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
world_address = "0x3fa8a26f275c4ec8ca5a34c9e33fa4c7ee568219421d3a9355ee086c1f8f620"
