#!/bin/bash
set -e
source scripts/setup.sh

export RPC_URL="https://api.cartridge.gg/x/starknet/mainnet"
export WORLD_ADDRESS=0x3fa8a26f275c4ec8ca5a34c9e33fa4c7ee568219421d3a9355ee086c1f8f620
export START_BLOCK=722385

torii --version
torii \
  --rpc $RPC_URL \
  --world $WORLD_ADDRESS $* \
  --start-block $START_BLOCK \
  --allowed-origins "*" \

