[package]
name = "karat"
version = "1.0.0"
cairo-version = "2.7.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "./migrate"
mint = "./scripts/mint.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.11" }
origami_token = { git = "https://github.com/rsodre/origami", branch = "karat" }
# origami_token = { git = "https://github.com/dojoengine/origami", tag = "v1.0.0-alpha.6" }


[[target.dojo]]
# to get the model names...
# cd /dojoengine/origami
# sozo build
# ls -l target/dev | grep model
build-external-contracts = [
  "origami_token::components::security::initializable::InitializableModel",
  "origami_token::components::introspection::src5::SRC5Model",
  # erc721
  "origami_token::components::token::erc721::erc721_owner::ERC721OwnerModel",
  "origami_token::components::token::erc721::erc721_balance::ERC721BalanceModel",
  "origami_token::components::token::erc721::erc721_metadata::ERC721MetaModel",
  "origami_token::components::token::erc721::erc721_enumerable::ERC721EnumerableIndexModel",
  "origami_token::components::token::erc721::erc721_enumerable::ERC721EnumerableOwnerIndexModel",
  "origami_token::components::token::erc721::erc721_enumerable::ERC721EnumerableOwnerTokenModel",
  "origami_token::components::token::erc721::erc721_enumerable::ERC721EnumerableTokenModel",
  "origami_token::components::token::erc721::erc721_enumerable::ERC721EnumerableTotalModel",
  "origami_token::components::token::erc721::erc721_approval::ERC721TokenApprovalModel",
  "origami_token::components::token::erc721::erc721_approval::ERC721OperatorApprovalModel",
  # erc20 (mock)
  "origami_token::components::token::erc20::erc20_balance::ERC20BalanceModel",
  "origami_token::components::token::erc20::erc20_metadata::ERC20MetadataModel",
  "origami_token::components::token::erc20::erc20_allowance::ERC20AllowanceModel",
  "origami_token::components::token::erc20::erc20_bridgeable::ERC20BridgeableModel",
]


#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.sepolia]
[profile.mainnet]
