[tool.dojo.world]
name = "512 Karat"
description = "Generative Art made with Dojo."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/rsodre/512karat"

[tool.dojo.world.socials]
x = "https://x.com/matalecode"
discord = "https://discord.gg/EWfmkemdyG"
github = "https://github.com/rsodre"
telegram = "https://t.me/mataleone"

[package]
cairo-version = "2.6.3"
name = "karat"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
mint = "./scripts/mint.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.0" }
token = { git = "https://github.com/rsodre/origami", branch = "karat" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "417c5a80ed2fef05ce159d643f3e34a5386ee06c" }

[[target.dojo]]
build-external-contracts = [
  "token::components::security::initializable::initializable_component",
  "token::components::token::erc721::erc721_approval::erc721_approval_component",
  "token::components::token::erc721::erc721_balance::erc721_balance_component",
  "token::components::token::erc721::erc721_burnable::erc721_burnable_component",
  "token::components::token::erc721::erc721_enumerable::erc721_enumerable_component",
  # "token::components::token::erc721::erc721_metadata::erc721_metadata_component",
  "token::components::token::erc721::erc721_mintable::erc721_mintable_component",
  "token::components::token::erc721::erc721_owner::erc721_owner_component",
]

[tool.dojo]
initializer_class_hash = "0xdeadcode"

[tool.dojo.env]
# world_address = ""

[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050"
world_address = "0x3e42a9746e6c8f868f71a4353ec5d198f0dd1af26f95bd51e2e005358ae14fd"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
