kind = "DojoContract"
class_hash = "0x247bdd41339a0d9b6b181c3f6a8943a9db091a700d58a3b5cc34a28f3248bd6"
original_class_hash = "0x247bdd41339a0d9b6b181c3f6a8943a9db091a700d58a3b5cc34a28f3248bd6"
base_class_hash = "0x0"
abi = "manifests/mainnet/abis/base/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"
