kind = "DojoContract"
class_hash = "0x4bc8242eb6cf9a94410b4a0e3e5fbeb09510d70ad097f8fe0a3a184fa951ade"
original_class_hash = "0x4bc8242eb6cf9a94410b4a0e3e5fbeb09510d70ad097f8fe0a3a184fa951ade"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = []
init_calldata = []
tag = "karat-minter"
systems = [
    "set_available",
    "set_purchase_price",
    "set_royalty",
    "_assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"
