[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x3fa8a26f275c4ec8ca5a34c9e33fa4c7ee568219421d3a9355ee086c1f8f620"
transaction_hash = "0x2a929ba5aac5d78f364e8903c32c9c466c6bc7dfa4847eba3df7c0df8777976"
block_number = 3
seed = "karat"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7d8ea58612a5de25f29281199a4fc1f2ce42f0f207f93c3a35280605f3b8e68"
class_hash = "0x7fcc518a71ac318b166d697ede3454335af09c2f8475b15fc237f48ad66a4b0"
original_class_hash = "0x7fcc518a71ac318b166d697ede3454335af09c2f8475b15fc237f48ad66a4b0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = [
    "origami_karat-SRC5Model",
    "origami_karat-InitializableModel",
    "origami_karat-ERC721OwnerModel",
    "origami_karat-ERC721BalanceModel",
    "origami_karat-ERC721MetaModel",
    "origami_karat-ERC721EnumerableIndexModel",
    "origami_karat-ERC721EnumerableOwnerIndexModel",
    "origami_karat-ERC721EnumerableOwnerTokenModel",
    "origami_karat-ERC721EnumerableTokenModel",
    "origami_karat-ERC721EnumerableTotalModel",
    "origami_karat-ERC721TokenApprovalModel",
    "origami_karat-ERC721OperatorApprovalModel",
]
init_calldata = []
tag = "karat-karat_token"
systems = [
    "mint",
    "burn",
    "karat_init",
    "emit_metadata_update",
    "emit_batch_metadata_update",
]
manifest_name = "karat-karat_token-6eea4d34"

[[contracts]]
kind = "DojoContract"
address = "0x14262b9314cfdcc76883e040cf232f2a139510f9c84f229f20da0f07d3b8b9b"
class_hash = "0x1ed6b52b827b9b6ff423dbb52c01b5c8cbe641d1cafcbb88dfd6253dccf8653"
original_class_hash = "0x1ed6b52b827b9b6ff423dbb52c01b5c8cbe641d1cafcbb88dfd6253dccf8653"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = [
    "karat-Config",
    "karat-Seed",
]
init_calldata = [
    "$contract_address:karat-karat_token",
    "512",
    "1",
]
tag = "karat-minter"
systems = [
    "set_available",
    "set_purchase_price",
    "set_royalty",
    "_assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"

[[models]]
kind = "DojoModel"
class_hash = "0x208ffca74448e858688c0a40d040dc4255edb9952ea7185711f3763c9b413b4"
original_class_hash = "0x208ffca74448e858688c0a40d040dc4255edb9952ea7185711f3763c9b413b4"
abi = "manifests/dev/deployment/abis/models/karat-Config-4fe722d0.json"
tag = "karat-Config"
qualified_path = "karat::models::config::config"
manifest_name = "karat-Config-4fe722d0"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "max_supply"
type = "u128"
key = false

[[models.members]]
name = "available_supply"
type = "u128"
key = false

[[models.members]]
name = "cool_down"
type = "bool"
key = false

[[models.members]]
name = "royalty_receiver"
type = "ContractAddress"
key = false

[[models.members]]
name = "royalty_fraction"
type = "u128"
key = false

[[models.members]]
name = "purchase_coin_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "purchase_price_eth"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
original_class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
abi = "manifests/dev/deployment/abis/models/karat-Seed-5904bdd8.json"
tag = "karat-Seed"
qualified_path = "karat::models::seed::seed"
manifest_name = "karat-Seed-5904bdd8"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4afc8a9db9e30cfb32c262778190aeb6b53d45fcb6dc8b6c455c462c2ab3542"
original_class_hash = "0x4afc8a9db9e30cfb32c262778190aeb6b53d45fcb6dc8b6c455c462c2ab3542"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC20AllowanceModel-3dd6a62f.json"
tag = "origami_karat-ERC20AllowanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_allowance::erc_20_allowance_model"
manifest_name = "origami_karat-ERC20AllowanceModel-3dd6a62f"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x63c13636f27db77008be1318900ec3c4e08f6cb1b3167d7dbd147f89ff2d4fb"
original_class_hash = "0x63c13636f27db77008be1318900ec3c4e08f6cb1b3167d7dbd147f89ff2d4fb"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC20BalanceModel-434aacb2.json"
tag = "origami_karat-ERC20BalanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_balance::erc_20_balance_model"
manifest_name = "origami_karat-ERC20BalanceModel-434aacb2"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4d42eba0c0ea583530693481ee899f7cedfa70ceefb67a328175c8bcb799d3e"
original_class_hash = "0x4d42eba0c0ea583530693481ee899f7cedfa70ceefb67a328175c8bcb799d3e"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC20BridgeableModel-47e92f47.json"
tag = "origami_karat-ERC20BridgeableModel"
qualified_path = "origami_token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model"
manifest_name = "origami_karat-ERC20BridgeableModel-47e92f47"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1ec2e5684b7c6fbdcf40e98a125447b1e383659091229f4795009b64822c595"
original_class_hash = "0x1ec2e5684b7c6fbdcf40e98a125447b1e383659091229f4795009b64822c595"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC20MetadataModel-57cc5c8d.json"
tag = "origami_karat-ERC20MetadataModel"
qualified_path = "origami_token::components::token::erc20::erc20_metadata::erc_20_metadata_model"
manifest_name = "origami_karat-ERC20MetadataModel-57cc5c8d"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
original_class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721BalanceModel-310d3b4b.json"
tag = "origami_karat-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "origami_karat-ERC721BalanceModel-310d3b4b"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6845784f221a8ebd916dadec974d486ce1d43f637484ece3f2430615ed54b6a"
original_class_hash = "0x6845784f221a8ebd916dadec974d486ce1d43f637484ece3f2430615ed54b6a"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721EnumerableIndexModel-2f673b2e.json"
tag = "origami_karat-ERC721EnumerableIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"
manifest_name = "origami_karat-ERC721EnumerableIndexModel-2f673b2e"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6591d013f5ac2840c72ff073667554ec9a370ca2ba443d0545673dd0021e428"
original_class_hash = "0x6591d013f5ac2840c72ff073667554ec9a370ca2ba443d0545673dd0021e428"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721EnumerableOwnerIndexModel-323d04e8.json"
tag = "origami_karat-ERC721EnumerableOwnerIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"
manifest_name = "origami_karat-ERC721EnumerableOwnerIndexModel-323d04e8"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
original_class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb.json"
tag = "origami_karat-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
original_class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721EnumerableTokenModel-46ae9a70.json"
tag = "origami_karat-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "origami_karat-ERC721EnumerableTokenModel-46ae9a70"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
original_class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721EnumerableTotalModel-4ef0f6e0.json"
tag = "origami_karat-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "origami_karat-ERC721EnumerableTotalModel-4ef0f6e0"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x245d514173e0e62b83bfe45e34f72901d677493a7a50497d0bf6f819259c595"
original_class_hash = "0x245d514173e0e62b83bfe45e34f72901d677493a7a50497d0bf6f819259c595"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721MetaModel-5b878968.json"
tag = "origami_karat-ERC721MetaModel"
qualified_path = "origami_token::components::token::erc721::erc721_metadata::erc_721_meta_model"
manifest_name = "origami_karat-ERC721MetaModel-5b878968"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e29a660fe1d206b03bbb264a6a97863186c723ad0bf20abcc92ae5040de985"
original_class_hash = "0x1e29a660fe1d206b03bbb264a6a97863186c723ad0bf20abcc92ae5040de985"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721OperatorApprovalModel-723f0a3d.json"
tag = "origami_karat-ERC721OperatorApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"
manifest_name = "origami_karat-ERC721OperatorApprovalModel-723f0a3d"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
original_class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721OwnerModel-25f64520.json"
tag = "origami_karat-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "origami_karat-ERC721OwnerModel-25f64520"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
original_class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
abi = "manifests/dev/deployment/abis/models/origami_karat-ERC721TokenApprovalModel-87684520.json"
tag = "origami_karat-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "origami_karat-ERC721TokenApprovalModel-87684520"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
original_class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
abi = "manifests/dev/deployment/abis/models/origami_karat-InitializableModel-79e5ed1c.json"
tag = "origami_karat-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_karat-InitializableModel-79e5ed1c"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5534950c83f5267cce9d7fc68b82362d9bf1f1322d00ad2ebd99f88aa30e808"
original_class_hash = "0x5534950c83f5267cce9d7fc68b82362d9bf1f1322d00ad2ebd99f88aa30e808"
abi = "manifests/dev/deployment/abis/models/origami_karat-SRC5Model-40cfc113.json"
tag = "origami_karat-SRC5Model"
qualified_path = "origami_token::components::introspection::src5::src_5_model"
manifest_name = "origami_karat-SRC5Model-40cfc113"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "interface_id"
type = "felt252"
key = true

[[models.members]]
name = "supports"
type = "bool"
key = false
