kind = "DojoModel"
class_hash = "0x44a95fb54f9ce628af8d3a9308f6da9331a3504c4e93122fd28988b41e82632"
original_class_hash = "0x44a95fb54f9ce628af8d3a9308f6da9331a3504c4e93122fd28988b41e82632"
abi = "manifests/mainnet/abis/base/models/karat_systems_metadata_erc_721_meta_model.json"
name = "karat::systems::metadata::erc_721_meta_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "base_uri"
type = "ByteArray"
key = false
