kind = "DojoModel"
class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
original_class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
abi = "manifests/mainnet/base/abis/models/origami_karat-InitializableModel-79e5ed1c.json"
tag = "origami_karat-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_karat-InitializableModel-79e5ed1c"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false
