kind = "DojoModel"
class_hash = "0x4d42eba0c0ea583530693481ee899f7cedfa70ceefb67a328175c8bcb799d3e"
original_class_hash = "0x4d42eba0c0ea583530693481ee899f7cedfa70ceefb67a328175c8bcb799d3e"
abi = "manifests/mainnet/base/abis/models/origami_karat-ERC20BridgeableModel-47e92f47.json"
tag = "origami_karat-ERC20BridgeableModel"
qualified_path = "origami_token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model"
manifest_name = "origami_karat-ERC20BridgeableModel-47e92f47"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false
