kind = "DojoModel"
class_hash = "0x604ffab2db12a3094c2ffb5e8791bb89d38621303a0a1220603274ab4336f4c"
original_class_hash = "0x604ffab2db12a3094c2ffb5e8791bb89d38621303a0a1220603274ab4336f4c"
abi = "manifests/sepolia/abis/base/models/karat_models_seed_seed.json"
name = "karat::models::seed::seed"

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "seed"
type = "u128"
key = false
