kind = "DojoModel"
class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
original_class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
abi = "manifests/sepolia/base/abis/models/origami_karat-ERC721EnumerableTotalModel-4ef0f6e0.json"
tag = "origami_karat-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "origami_karat-ERC721EnumerableTotalModel-4ef0f6e0"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "total_supply"
type = "u128"
key = false
