kind = "DojoModel"
class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
original_class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
abi = "manifests/sepolia/base/abis/models/origami_karat-ERC721BalanceModel-310d3b4b.json"
tag = "origami_karat-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "origami_karat-ERC721BalanceModel-310d3b4b"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "account"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
