kind = "DojoModel"
class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
original_class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
abi = "manifests/sepolia/base/abis/models/origami_karat-ERC721TokenApprovalModel-87684520.json"
tag = "origami_karat-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "origami_karat-ERC721TokenApprovalModel-87684520"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
