kind = "DojoModel"
class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
original_class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
abi = "manifests/sepolia/base/abis/models/origami_karat-ERC721EnumerableTokenModel-46ae9a70.json"
tag = "origami_karat-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "origami_karat-ERC721EnumerableTokenModel-46ae9a70"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u128"
key = false
