kind = "DojoModel"
class_hash = "0x5f6fb131126f3aef7ecfc43a34c5ee412990658b540e5194e25c731f813bbe7"
original_class_hash = "0x5f6fb131126f3aef7ecfc43a34c5ee412990658b540e5194e25c731f813bbe7"
abi = "manifests/dev/abis/base/models/karat_models_moves_moves.json"
name = "karat::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
