kind = "DojoModel"
class_hash = "0xe95c66e083e2544e59253769427187d7e3b046326261277454c67bcc7af4d0"
original_class_hash = "0xe95c66e083e2544e59253769427187d7e3b046326261277454c67bcc7af4d0"
abi = "manifests/dev/base/abis/models/karat-Config-4fe722d0.json"
tag = "karat-Config"
qualified_path = "karat::models::config::config"
manifest_name = "karat-Config-4fe722d0"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[members]]
name = "max_supply"
type = "u128"
key = false

[[members]]
name = "available_supply"
type = "u128"
key = false

[[members]]
name = "cool_down"
type = "bool"
key = false
