kind = "DojoModel"
class_hash = "0x7ced01e1507099f4408f1596c2116c6ee7d7e6f0f5f7c26bca0b9b245f793eb"
original_class_hash = "0x7ced01e1507099f4408f1596c2116c6ee7d7e6f0f5f7c26bca0b9b245f793eb"
abi = "manifests/dev/abis/base/models/karat_models_config_config.json"
name = "karat::models::config::config"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[members]]
name = "painter_address"
type = "ContractAddress"
key = false

[[members]]
name = "max_supply"
type = "u128"
key = false

[[members]]
name = "cool_down"
type = "bool"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
