kind = "DojoModel"
class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
original_class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
abi = "manifests/dev/base/abis/models/origami_karat-ERC721OwnerModel-25f64520.json"
tag = "origami_karat-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "origami_karat-ERC721OwnerModel-25f64520"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
