kind = "DojoModel"
class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
original_class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
abi = "manifests/dev/base/abis/models/origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb.json"
tag = "origami_karat-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u128"
key = false
