[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/mainnet/deployment/abis/dojo-world.json"
address = "0x3fa8a26f275c4ec8ca5a34c9e33fa4c7ee568219421d3a9355ee086c1f8f620"
transaction_hash = "0x7e075b3a7ed9d2f6d02de223942a44a712494c0c5ef5de80f6ec651db4f6d63"
seed = "karat"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "mainnet"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7d8ea58612a5de25f29281199a4fc1f2ce42f0f207f93c3a35280605f3b8e68"
class_hash = "0x890c0eeb11aeb41f237343c3e88b199a2e7e0c159debd1e9c232652afe5dc2"
original_class_hash = "0x890c0eeb11aeb41f237343c3e88b199a2e7e0c159debd1e9c232652afe5dc2"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = [
    "origami_karat-SRC5Model",
    "origami_karat-InitializableModel",
    "origami_karat-ERC721OwnerModel",
    "origami_karat-ERC721BalanceModel",
    "origami_karat-ERC721MetaModel",
    "origami_karat-ERC721EnumerableIndexModel",
    "origami_karat-ERC721EnumerableOwnerIndexModel",
    "origami_karat-ERC721EnumerableOwnerTokenModel",
    "origami_karat-ERC721EnumerableTokenModel",
    "origami_karat-ERC721EnumerableTotalModel",
    "origami_karat-ERC721TokenApprovalModel",
    "origami_karat-ERC721OperatorApprovalModel",
]
init_calldata = []
tag = "karat-karat_token"
systems = [
    "mint",
    "burn",
]
manifest_name = "karat-karat_token-6eea4d34"

[[contracts]]
kind = "DojoContract"
address = "0x14262b9314cfdcc76883e040cf232f2a139510f9c84f229f20da0f07d3b8b9b"
class_hash = "0xdec91d322af256032e9ab4a8f70447332d4f45da75c377cbcaa6adf71a7973"
original_class_hash = "0xdec91d322af256032e9ab4a8f70447332d4f45da75c377cbcaa6adf71a7973"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/mainnet/deployment/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = [
    "karat-Config",
    "karat-Seed",
]
init_calldata = [
    "$contract_address:karat-karat_token",
    "512",
    "0",
]
tag = "karat-minter"
systems = [
    "set_available",
    "assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"

[[models]]
kind = "DojoModel"
class_hash = "0xe95c66e083e2544e59253769427187d7e3b046326261277454c67bcc7af4d0"
original_class_hash = "0xe95c66e083e2544e59253769427187d7e3b046326261277454c67bcc7af4d0"
abi = "manifests/mainnet/deployment/abis/models/karat-Config-4fe722d0.json"
tag = "karat-Config"
qualified_path = "karat::models::config::config"
manifest_name = "karat-Config-4fe722d0"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "minter_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "renderer_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "max_supply"
type = "u128"
key = false

[[models.members]]
name = "available_supply"
type = "u128"
key = false

[[models.members]]
name = "cool_down"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
original_class_hash = "0x6ed4b9bc3eabae89e10ec9d3c527c6867b3b310612bfb1513f595e476873012"
abi = "manifests/mainnet/deployment/abis/models/karat-Seed-5904bdd8.json"
tag = "karat-Seed"
qualified_path = "karat::models::seed::seed"
manifest_name = "karat-Seed-5904bdd8"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
original_class_hash = "0x730809cf076982eef7705be526e16a5821a0ccbc2a9dee431f0f836d95bfb47"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721BalanceModel-310d3b4b.json"
tag = "origami_karat-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "origami_karat-ERC721BalanceModel-310d3b4b"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6845784f221a8ebd916dadec974d486ce1d43f637484ece3f2430615ed54b6a"
original_class_hash = "0x6845784f221a8ebd916dadec974d486ce1d43f637484ece3f2430615ed54b6a"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721EnumerableIndexModel-2f673b2e.json"
tag = "origami_karat-ERC721EnumerableIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"
manifest_name = "origami_karat-ERC721EnumerableIndexModel-2f673b2e"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6591d013f5ac2840c72ff073667554ec9a370ca2ba443d0545673dd0021e428"
original_class_hash = "0x6591d013f5ac2840c72ff073667554ec9a370ca2ba443d0545673dd0021e428"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721EnumerableOwnerIndexModel-323d04e8.json"
tag = "origami_karat-ERC721EnumerableOwnerIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"
manifest_name = "origami_karat-ERC721EnumerableOwnerIndexModel-323d04e8"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
original_class_hash = "0x66e476c25b0d17546f3c87fa0b353e2dc446d7e664fe44bb1355558c49e492f"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb.json"
tag = "origami_karat-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "origami_karat-ERC721EnumerableOwnerTokenModel-4b4f3beb"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
original_class_hash = "0x1e2561e8f1cad22840c39a0b20ca1514d11265cf5fa1832e43675e23c88124a"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721EnumerableTokenModel-46ae9a70.json"
tag = "origami_karat-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "origami_karat-ERC721EnumerableTokenModel-46ae9a70"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
original_class_hash = "0x3bd5a95d8ba6c91b6ee50affe73d427651257b3bd4ae881aee17138e7f0ba5f"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721EnumerableTotalModel-4ef0f6e0.json"
tag = "origami_karat-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "origami_karat-ERC721EnumerableTotalModel-4ef0f6e0"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x245d514173e0e62b83bfe45e34f72901d677493a7a50497d0bf6f819259c595"
original_class_hash = "0x245d514173e0e62b83bfe45e34f72901d677493a7a50497d0bf6f819259c595"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721MetaModel-5b878968.json"
tag = "origami_karat-ERC721MetaModel"
qualified_path = "origami_token::components::token::erc721::erc721_metadata::erc_721_meta_model"
manifest_name = "origami_karat-ERC721MetaModel-5b878968"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e29a660fe1d206b03bbb264a6a97863186c723ad0bf20abcc92ae5040de985"
original_class_hash = "0x1e29a660fe1d206b03bbb264a6a97863186c723ad0bf20abcc92ae5040de985"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721OperatorApprovalModel-723f0a3d.json"
tag = "origami_karat-ERC721OperatorApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"
manifest_name = "origami_karat-ERC721OperatorApprovalModel-723f0a3d"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
original_class_hash = "0xccdd862153020ce7680e7a6efa3a73743337293cbb2f7d219ab2de1be899fc"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721OwnerModel-25f64520.json"
tag = "origami_karat-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "origami_karat-ERC721OwnerModel-25f64520"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
original_class_hash = "0x28b413c3ab4ecdfea7e4a3cdb318835fcde26a4acb1803386c6b81c927732bd"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-ERC721TokenApprovalModel-87684520.json"
tag = "origami_karat-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "origami_karat-ERC721TokenApprovalModel-87684520"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
original_class_hash = "0x181f798c43df3b3646ae4966f257fdbabb994d8618c82e0d923fd643b8437a6"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-InitializableModel-79e5ed1c.json"
tag = "origami_karat-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_karat-InitializableModel-79e5ed1c"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5534950c83f5267cce9d7fc68b82362d9bf1f1322d00ad2ebd99f88aa30e808"
original_class_hash = "0x5534950c83f5267cce9d7fc68b82362d9bf1f1322d00ad2ebd99f88aa30e808"
abi = "manifests/mainnet/deployment/abis/models/origami_karat-SRC5Model-40cfc113.json"
tag = "origami_karat-SRC5Model"
qualified_path = "origami_token::components::introspection::src5::src_5_model"
manifest_name = "origami_karat-SRC5Model-40cfc113"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "interface_id"
type = "felt252"
key = true

[[models.members]]
name = "supports"
type = "bool"
key = false
