kind = "DojoContract"
class_hash = "0x1a854cf649a3f6d06b300f343d978ebe3082628e3bd9b921589b11714effad"
original_class_hash = "0x1a854cf649a3f6d06b300f343d978ebe3082628e3bd9b921589b11714effad"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::actions::actions"
