kind = "DojoContract"
class_hash = "0x625c807cbdf7c297d3c511864b82f84f386359e318b52bf1b7b6ae0358db83"
original_class_hash = "0x625c807cbdf7c297d3c511864b82f84f386359e318b52bf1b7b6ae0358db83"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = []
init_calldata = []
tag = "karat-minter"
systems = [
    "set_available",
    "assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"
