kind = "DojoContract"
class_hash = "0x6652aadafa3e073ac7829c8a423021d962fba14f1c736ccc9e6b632c15de64d"
original_class_hash = "0x6652aadafa3e073ac7829c8a423021d962fba14f1c736ccc9e6b632c15de64d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = []
init_calldata = []
tag = "karat-minter"
systems = [
    "set_open",
    "assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"
