kind = "DojoContract"
class_hash = "0x32fdecd54a4426060bfdda844976c34d7d7b14e06379fbd0cce2b0af12dec60"
original_class_hash = "0x32fdecd54a4426060bfdda844976c34d7d7b14e06379fbd0cce2b0af12dec60"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"
