kind = "DojoContract"
class_hash = "0xd93c85c689eb2a0d3cfe34ba1397c414056efe654da77d290378dae657a651"
original_class_hash = "0xd93c85c689eb2a0d3cfe34ba1397c414056efe654da77d290378dae657a651"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = []
init_calldata = []
tag = "karat-karat_token"
systems = [
    "initialize",
    "mint",
    "burn",
]
manifest_name = "karat-karat_token-6eea4d34"
