kind = "DojoContract"
class_hash = "0x1ed6b52b827b9b6ff423dbb52c01b5c8cbe641d1cafcbb88dfd6253dccf8653"
original_class_hash = "0x1ed6b52b827b9b6ff423dbb52c01b5c8cbe641d1cafcbb88dfd6253dccf8653"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/karat-minter-2f247449.json"
reads = []
writes = []
init_calldata = []
tag = "karat-minter"
systems = [
    "set_available",
    "set_purchase_price",
    "set_royalty",
    "_assert_caller_is_owner",
]
manifest_name = "karat-minter-2f247449"
