kind = "DojoContract"
class_hash = "0x6141e72771227c75ec6f6f6f45305c24c0f45792a2100ff59cb7b22edd62894"
original_class_hash = "0x6141e72771227c75ec6f6f6f45305c24c0f45792a2100ff59cb7b22edd62894"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"
