kind = "DojoContract"
class_hash = "0x837646492e53d1691bb796e1f90a13262c2f60c843fbfb02cc6773a96823ef"
original_class_hash = "0x837646492e53d1691bb796e1f90a13262c2f60c843fbfb02cc6773a96823ef"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::minter::minter"
