kind = "DojoContract"
class_hash = "0x7439affc76abdd5c9b330badc87942f4673df587d8210ced4abb367f9985381"
original_class_hash = "0x7439affc76abdd5c9b330badc87942f4673df587d8210ced4abb367f9985381"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::minter::minter"
