kind = "DojoContract"
class_hash = "0x64e7316877d02b768682b76a88b95a2005bd9577e715d58f7fd070ec27142da"
original_class_hash = "0x64e7316877d02b768682b76a88b95a2005bd9577e715d58f7fd070ec27142da"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/karat-karat_token-6eea4d34.json"
reads = []
writes = []
init_calldata = []
tag = "karat-karat_token"
systems = [
    "mint",
    "burn",
]
manifest_name = "karat-karat_token-6eea4d34"
