kind = "DojoContract"
class_hash = "0xecdb9b73b6cdaeea32aa1f5335944580a36e782fc821878f2af7d78acd35ea"
original_class_hash = "0xecdb9b73b6cdaeea32aa1f5335944580a36e782fc821878f2af7d78acd35ea"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::minter::minter"
