kind = "DojoContract"
class_hash = "0x5cd55688e79ac25f624d8bcab54db990ae0239e79cc82a6fc0df5275ab638b2"
original_class_hash = "0x5cd55688e79ac25f624d8bcab54db990ae0239e79cc82a6fc0df5275ab638b2"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_tests_token_erc721_metadata_mock_erc721_metadata_mock.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::tests::token::erc721_metadata_mock::erc721_metadata_mock"
