kind = "DojoContract"
class_hash = "0x42a35c9659c12796cff9036e8d94fa6dc42b867c6d3a7610b7a76b5d5291dd0"
original_class_hash = "0x42a35c9659c12796cff9036e8d94fa6dc42b867c6d3a7610b7a76b5d5291dd0"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_karat_token_karat_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::karat_token::karat_token"
