kind = "DojoContract"
class_hash = "0x2fa9779689b221504d3d165d1d41abb316f4b088eff0117666699403cd03e0d"
original_class_hash = "0x2fa9779689b221504d3d165d1d41abb316f4b088eff0117666699403cd03e0d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/karat_systems_minter_minter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "karat::systems::minter::minter"
